Algoritmo "1, 2, 1, 4..."
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Adani e Luciana
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    :Flavio Brandão N°11 e Lucca Luigi Nº25
// Data atual  : 02/08/2019
Var
x, y: real

Inicio
      y:=0
      x:=1
      ENQUANTO (y<100)FACA
              y:=y+2
              escreval(x, ",", y)
      fimenquanto

Fimalgoritmo